#!/bin/sh

# export `xinput list | grep -i touchpad | awk '{ print $6 }'`
# xinput --set-prop "$id" "Synaptics Noise Cancellation" 20 20
# xinput --set-prop "$id" "Synaptics Finger" 35 45 250
# xinput --set-prop "$id" "Synaptics Scrolling Distance" 180 180
# true


# LS touchpad settings
# xinput list-props 13
xinput set-prop 12 152 1
xinput set-prop 12 291 1
xinput set-prop 12 311 1


#xinput set-prop 13 152 1
#xinput set-prop 13 309 1
#xinput set-prop 13 296 1

# set touchpad property tapping
# xinput set-prop 13 291 1

xset r rate 220 40
